/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AlunoController;
import Model.CadastroAlunoModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tylui
 */
public class AlunoView extends javax.swing.JFrame {

    /**
     * Creates new form AlunoView
     */
    private static int id = 1;
    private int linha = 0;
    private int CodigoEdit = 0;
    private boolean Editar = true;
    
    public AlunoView() {
        initComponents();
        jbEditarAluno.setEnabled(false);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAluno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAluno = new javax.swing.JTable();
        Warning = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Lampada = new javax.swing.JLabel();
        PainelPesquisa = new javax.swing.JPanel();
        jtxPesquisaAluno = new javax.swing.JTextField();
        jbPesquisarAluno = new javax.swing.JButton();
        jbNovoAluno = new javax.swing.JButton();
        jbEditarAluno = new javax.swing.JButton();
        jbCancelarAluno = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiAluno = new javax.swing.JMenuItem();
        jmiInstrutores = new javax.swing.JMenuItem();
        jmiTreinos = new javax.swing.JMenuItem();
        jmiEquipamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fabrica de Monstros - Dados dos alunos");
        setResizable(false);

        TabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Sexo", "CPF", "Logadouro", "Bairro", "Numero", "Cidade", "Horario", "Estado", "Peso corporal", "Estatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAluno.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TabelaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAlunoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaAluno);

        javax.swing.GroupLayout PainelAlunoLayout = new javax.swing.GroupLayout(PainelAluno);
        PainelAluno.setLayout(PainelAlunoLayout);
        PainelAlunoLayout.setHorizontalGroup(
            PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        PainelAlunoLayout.setVerticalGroup(
            PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlunoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        Warning.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Warning.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Voce no momento esta \nno cadastro dos alunos");
        Warning.setViewportView(jTextArea1);

        Lampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/alerta.png"))); // NOI18N

        PainelPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        PainelPesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPesquisarAluno.setText("Pesquisar");
        jbPesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPesquisaLayout = new javax.swing.GroupLayout(PainelPesquisa);
        PainelPesquisa.setLayout(PainelPesquisaLayout);
        PainelPesquisaLayout.setHorizontalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxPesquisaAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarAluno))
        );
        PainelPesquisaLayout.setVerticalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxPesquisaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarAluno))
                .addContainerGap())
        );

        jbNovoAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbNovoAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/novo.png"))); // NOI18N
        jbNovoAluno.setText("Novo ");
        jbNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoAlunoActionPerformed(evt);
            }
        });

        jbEditarAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbEditarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/editar.png"))); // NOI18N
        jbEditarAluno.setText("Editar ");
        jbEditarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarAlunoActionPerformed(evt);
            }
        });

        jbCancelarAluno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelarAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/cancelar.png"))); // NOI18N
        jbCancelarAluno.setText("Cancelar ");
        jbCancelarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarAlunoActionPerformed(evt);
            }
        });

        jmCadastro.setText("Cadastro");

        jmiAluno.setText("Alunos");
        jmiAluno.setEnabled(false);
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiAluno);

        jmiInstrutores.setText("Instrutores");
        jmiInstrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInstrutoresActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiInstrutores);

        jmiTreinos.setText("Treinos");
        jmiTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTreinosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiTreinos);

        jmiEquipamentos.setText("Equipamentos");
        jmiEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEquipamentosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiEquipamentos);

        jMenu.add(jmCadastro);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lampada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNovoAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditarAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelarAluno)
                        .addGap(0, 297, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lampada))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PainelAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNovoAluno)
                            .addComponent(jbEditarAluno)
                            .addComponent(jbCancelarAluno))
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbCancelarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarAlunoActionPerformed
        // TODO add your handling code here:
        dispose();
        Principal inicio = new Principal();
        inicio.setVisible(true);
    }//GEN-LAST:event_jbCancelarAlunoActionPerformed

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
        // TODO add your handling code here:
        AlunoView aluno = new AlunoView();
        aluno.setVisible(true);
    }//GEN-LAST:event_jmiAlunoActionPerformed

    private void jmiInstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstrutoresActionPerformed
        // TODO add your handling code here:
        InstrutoresView instrutores = new InstrutoresView();
        instrutores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiInstrutoresActionPerformed

    private void jmiTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTreinosActionPerformed
        // TODO add your handling code here:
        TreinoView treino = new TreinoView();
        treino.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiTreinosActionPerformed

    private void jmiEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEquipamentosActionPerformed
        // TODO add your handling code here:
        EquipamentosView equipamentos = new EquipamentosView();
        equipamentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiEquipamentosActionPerformed

    private void jbNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoAlunoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroAluno newAluno = new CadastroAluno();
        newAluno.setVisible(true);
    }//GEN-LAST:event_jbNovoAlunoActionPerformed

    private void jbEditarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarAlunoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroAluno editeAluno = new CadastroAluno();
        editeAluno.setVisible(true);
        editeAluno.recebeDados(CodigoEdit, Editar);
    }//GEN-LAST:event_jbEditarAlunoActionPerformed

    private void TabelaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAlunoMouseClicked
        // TODO add your handling code here:
        linha = TabelaAluno.getSelectedRow();
        jbEditarAluno.setEnabled(true);
        CodigoEdit = Integer.parseInt((String)TabelaAluno.getValueAt(linha, 0));
    }//GEN-LAST:event_TabelaAlunoMouseClicked

    private void jbPesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarAlunoActionPerformed
        // TODO add your handling code here:
        if (!jtxPesquisaAluno.getText().trim().equals("")){
            CadastroAlunoModel aluno = new CadastroAlunoModel();
            aluno.setNomeAluno(jtxPesquisaAluno.getText());
            AlunoController controller = new AlunoController();
            ArrayList<CadastroAlunoModel> lista = controller.selecionarTodosNomesAlunos(aluno);
            if(!lista.isEmpty()){
                DefaultTableModel modelo = (DefaultTableModel)TabelaAluno.getModel();
                modelo.setRowCount(0);
                for(CadastroAlunoModel a: lista){
                    modelo.addRow(new String[]{
                        String.valueOf(a.getCodigoAluno()),
                        a.getNomeAluno(),
                        a.getSexoAluno(),
                        a.getCpfAluno(),
                        a.getRuaAluno(),
                        a.getBairroAluno(),
                        String.valueOf(a.getNumeroAluno()),
                        a.getCidadeAluno(),
                        a.getHorarioAluno(),
                        a.getEstadoAluno(),
                        String.valueOf(a.getPesoCorporal()),
                        String.valueOf(a.getEstatura())
                    });
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Pesquisar", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbPesquisarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void atualizarTabela(){
        AlunoController aluno = new AlunoController();
        ArrayList<CadastroAlunoModel> lista = aluno.selecionarTodosAlunos();
        if(!lista.isEmpty()){
            DefaultTableModel modelo = (DefaultTableModel)TabelaAluno.getModel();
            modelo.setRowCount(0);
            for(CadastroAlunoModel a: lista){
                modelo.addRow(new String[]{
                    String.valueOf(a.getCodigoAluno()),
                    a.getNomeAluno(),
                    a.getSexoAluno(),
                    a.getCpfAluno(),
                    a.getRuaAluno(),
                    a.getBairroAluno(),
                    String.valueOf(a.getNumeroAluno()),
                    a.getCidadeAluno(),
                    a.getHorarioAluno(),
                    a.getEstadoAluno(),
                    String.valueOf(a.getPesoCorporal()),
                    String.valueOf(a.getEstatura())
                });
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lampada;
    private javax.swing.JPanel PainelAluno;
    private javax.swing.JPanel PainelPesquisa;
    private javax.swing.JTable TabelaAluno;
    private javax.swing.JScrollPane Warning;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbCancelarAluno;
    private javax.swing.JButton jbEditarAluno;
    private javax.swing.JButton jbNovoAluno;
    private javax.swing.JButton jbPesquisarAluno;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiEquipamentos;
    private javax.swing.JMenuItem jmiInstrutores;
    private javax.swing.JMenuItem jmiTreinos;
    private javax.swing.JTextField jtxPesquisaAluno;
    // End of variables declaration//GEN-END:variables
}
