/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EquipamentoController;
import Model.CadastroEquipamentoModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tylui
 */
public class CadastroEquipamento extends javax.swing.JFrame {

    /**
     * Creates new form CadastroEquipamento
     */
    int CodigoEditEquip = 0;
    boolean Editar = false;
    
    public CadastroEquipamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDanificado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jbSairEquipe = new javax.swing.JButton();
        jbSalvarEquipe = new javax.swing.JButton();
        jbLimparEquipe = new javax.swing.JButton();
        jlDesccricao = new javax.swing.JLabel();
        jtxDescricaoEquipe = new javax.swing.JTextField();
        jlMarca = new javax.swing.JLabel();
        jtxMarcaEquipe = new javax.swing.JTextField();
        jlModelo = new javax.swing.JLabel();
        jtxModeloEquipe = new javax.swing.JTextField();
        jlPesoLimite = new javax.swing.JLabel();
        jlTipoUso = new javax.swing.JLabel();
        jtxTipoUsoEquipe = new javax.swing.JTextField();
        jlDanificado = new javax.swing.JLabel();
        jrSimEquipe = new javax.swing.JRadioButton();
        jrNaoEquipe = new javax.swing.JRadioButton();
        jtxPesoEquipe = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fábrica de Monstros - Cadastro de equipamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jbSairEquipe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSairEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/sair.png"))); // NOI18N
        jbSairEquipe.setText("Sair ");
        jbSairEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairEquipeActionPerformed(evt);
            }
        });

        jbSalvarEquipe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSalvarEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/salvar.png"))); // NOI18N
        jbSalvarEquipe.setText("Salvar ");
        jbSalvarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarEquipeActionPerformed(evt);
            }
        });

        jbLimparEquipe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLimparEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/limpar.png"))); // NOI18N
        jbLimparEquipe.setText("Limpar campos");
        jbLimparEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparEquipeActionPerformed(evt);
            }
        });

        jlDesccricao.setText("Descrição:");

        jlMarca.setText("Marca:");

        jlModelo.setText("Modelo:");

        jlPesoLimite.setText("Peso limite:");

        jlTipoUso.setText("Tipo de uso:");

        jlDanificado.setText("Danificado:");

        grupoDanificado.add(jrSimEquipe);
        jrSimEquipe.setText("Sim");

        grupoDanificado.add(jrNaoEquipe);
        jrNaoEquipe.setText("Nao");

        jtxPesoEquipe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSalvarEquipe)
                        .addGap(18, 18, 18)
                        .addComponent(jbLimparEquipe)
                        .addGap(18, 18, 18)
                        .addComponent(jbSairEquipe))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDesccricao)
                            .addComponent(jlMarca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxDescricaoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxPesoEquipe)
                                        .addGap(70, 70, 70)
                                        .addComponent(jlTipoUso))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxMarcaEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(jlModelo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxModeloEquipe)
                                    .addComponent(jtxTipoUsoEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlDanificado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrSimEquipe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrNaoEquipe))
                    .addComponent(jlPesoLimite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDesccricao)
                            .addComponent(jtxDescricaoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlMarca)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtxMarcaEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlModelo)
                                .addComponent(jtxModeloEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesoLimite)
                            .addComponent(jlTipoUso)
                            .addComponent(jtxTipoUsoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxPesoEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDanificado)
                            .addComponent(jrSimEquipe)
                            .addComponent(jrNaoEquipe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSalvarEquipe)
                            .addComponent(jbSairEquipe)
                            .addComponent(jbLimparEquipe)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarEquipeActionPerformed
        // TODO add your handling code here:
        if (!Editar){
            if((!jtxDescricaoEquipe.getText().trim().equals(""))&& (jrSimEquipe.isSelected() || jrNaoEquipe.isSelected())){
                CadastroEquipamentoModel equipamento = new CadastroEquipamentoModel();
                equipamento.setDescricaoEquipamento(jtxDescricaoEquipe.getText());
                equipamento.setMarcaEquipamento(jtxMarcaEquipe.getText());
                equipamento.setModeloEquipamento(jtxModeloEquipe.getText());
                equipamento.setPesoEquipamento(jtxPesoEquipe.getText());
                equipamento.setTipoEquipamento(jtxTipoUsoEquipe.getText());
                if (jrSimEquipe.isSelected())
                    equipamento.setDanificadoEquipamento(jrSimEquipe.getText());
                if (jrNaoEquipe.isSelected())
                    equipamento.setDanificadoEquipamento(jrNaoEquipe.getText());
                EquipamentoController controle = new EquipamentoController();
                if(controle.inserirEquipamento(equipamento)){
                    JOptionPane.showMessageDialog(this, "Equipamento salvo com sucesso!");
                    jbLimparEquipeActionPerformed(evt);
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao salvar Equipamento!", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
                }       
           }else{
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Equipamento! Campos Incompletos", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            if((!jtxDescricaoEquipe.getText().trim().equals(""))&& (jrSimEquipe.isSelected() || jrNaoEquipe.isSelected())){
                CadastroEquipamentoModel equipamento = new CadastroEquipamentoModel();
                equipamento.setCodigoEquipamento(CodigoEditEquip);
                equipamento.setDescricaoEquipamento(jtxDescricaoEquipe.getText());
                equipamento.setMarcaEquipamento(jtxMarcaEquipe.getText());
                equipamento.setModeloEquipamento(jtxModeloEquipe.getText());
                equipamento.setPesoEquipamento(jtxPesoEquipe.getText());
                equipamento.setTipoEquipamento(jtxTipoUsoEquipe.getText());
                if (jrSimEquipe.isSelected())
                    equipamento.setDanificadoEquipamento(jrSimEquipe.getText());
                if (jrNaoEquipe.isSelected())
                    equipamento.setDanificadoEquipamento(jrNaoEquipe.getText());
                EquipamentoController controle = new EquipamentoController();
                if(controle.editarEquipamento(equipamento)){
                    JOptionPane.showMessageDialog(this, "Equipamento editado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao Editar Equipamento!", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
                }       
           }else{
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Equipamento! Campos Incompletos", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
            EquipamentosView equipamento = new EquipamentosView();
            equipamento.setVisible(true);
            Editar = false;
            CodigoEditEquip = 0;
        }
            
    }//GEN-LAST:event_jbSalvarEquipeActionPerformed

    private void jbLimparEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparEquipeActionPerformed
        // TODO add your handling code here:
        jtxDescricaoEquipe.setText("");
        jtxMarcaEquipe.setText("");
        jtxModeloEquipe.setText("");
        jtxPesoEquipe.setText("");
        jtxTipoUsoEquipe.setText("");
        grupoDanificado.clearSelection();
    }//GEN-LAST:event_jbLimparEquipeActionPerformed

    private void jbSairEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairEquipeActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Se você sair irá perder todos os dados informados, deseja continuar?")==0){
            dispose();
            EquipamentosView equipamento = new EquipamentosView();
            equipamento.setVisible(true);
        } 
    }//GEN-LAST:event_jbSairEquipeActionPerformed

    /**
     * @param args the command line arguments
     */
    void recebeDados(int CodigoEquip, boolean EditarEquip){
        CodigoEditEquip = CodigoEquip;
        Editar = EditarEquip;
        CadastroEquipamentoModel equipamento = new CadastroEquipamentoModel();
        equipamento.setCodigoEquipamento(CodigoEditEquip);
        EquipamentoController controle = new EquipamentoController();
        equipamento = controle.selecionarEquipamento(equipamento);
        if(equipamento != null){
            jtxDescricaoEquipe.setText(equipamento.getDescricaoEquipamento());
            jtxMarcaEquipe.setText(equipamento.getMarcaEquipamento());
            jtxModeloEquipe.setText(equipamento.getModeloEquipamento());
            jtxPesoEquipe.setText(equipamento.getPesoEquipamento());
            jtxTipoUsoEquipe.setText(equipamento.getTipoEquipamento());
        }else{
            JOptionPane.showMessageDialog(this, "Equipamento não encontrado!", 
                        "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoDanificado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbLimparEquipe;
    private javax.swing.JButton jbSairEquipe;
    private javax.swing.JButton jbSalvarEquipe;
    private javax.swing.JLabel jlDanificado;
    private javax.swing.JLabel jlDesccricao;
    private javax.swing.JLabel jlMarca;
    private javax.swing.JLabel jlModelo;
    private javax.swing.JLabel jlPesoLimite;
    private javax.swing.JLabel jlTipoUso;
    private javax.swing.JRadioButton jrNaoEquipe;
    private javax.swing.JRadioButton jrSimEquipe;
    private javax.swing.JTextField jtxDescricaoEquipe;
    private javax.swing.JTextField jtxMarcaEquipe;
    private javax.swing.JTextField jtxModeloEquipe;
    private javax.swing.JFormattedTextField jtxPesoEquipe;
    private javax.swing.JTextField jtxTipoUsoEquipe;
    // End of variables declaration//GEN-END:variables
}
