/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AlunoController;
import Model.CadastroAlunoModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tylui
 */
public class CadastroAluno extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAluno
     */
    int CodigoEditAluno = 0;
    boolean Editar = false;
    
    public CadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PainelAluno = new javax.swing.JPanel();
        jlNome = new javax.swing.JLabel();
        jtxNome = new javax.swing.JTextField();
        jrMasculino = new javax.swing.JRadioButton();
        jrFeminino = new javax.swing.JRadioButton();
        jlRua = new javax.swing.JLabel();
        jtxRua = new javax.swing.JTextField();
        jlBairro = new javax.swing.JLabel();
        jtxBairro = new javax.swing.JTextField();
        jlNumero = new javax.swing.JLabel();
        jtxNumero = new javax.swing.JTextField();
        jlCPF = new javax.swing.JLabel();
        jtxCPF = new javax.swing.JFormattedTextField();
        jlCidade = new javax.swing.JLabel();
        jtxCidade = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox<>();
        jlHorario = new javax.swing.JLabel();
        jcbHorario = new javax.swing.JComboBox<>();
        jbLimparAlunoDado = new javax.swing.JButton();
        PainelAvaliacao = new javax.swing.JPanel();
        jlPesoCorporal = new javax.swing.JLabel();
        jtxPesoCorporal = new javax.swing.JFormattedTextField();
        jlEstatura = new javax.swing.JLabel();
        jtxEstatura = new javax.swing.JFormattedTextField();
        jlGordura = new javax.swing.JLabel();
        jlTriceps = new javax.swing.JLabel();
        jtxTriceps = new javax.swing.JFormattedTextField();
        jlSubescapular = new javax.swing.JLabel();
        jtxSubescapular = new javax.swing.JFormattedTextField();
        jlAbdominal = new javax.swing.JLabel();
        jtxAbdominal = new javax.swing.JFormattedTextField();
        jlSupra = new javax.swing.JLabel();
        jtxSupra = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jtxGordura = new javax.swing.JTextField();
        jlMusculo = new javax.swing.JLabel();
        jtxMusculo = new javax.swing.JTextField();
        jlImc = new javax.swing.JLabel();
        jtxImc = new javax.swing.JTextField();
        jlPesoMagro = new javax.swing.JLabel();
        jtxPesoMagro = new javax.swing.JTextField();
        jlPesoMuscular = new javax.swing.JLabel();
        jtxPesoMuscular = new javax.swing.JTextField();
        jlPesoGordo = new javax.swing.JLabel();
        jtxPesoGordo = new javax.swing.JTextField();
        jlPesoResidual = new javax.swing.JLabel();
        jtxPesoResidual = new javax.swing.JTextField();
        jlPesoOsseo = new javax.swing.JLabel();
        jtxPesoOsseo = new javax.swing.JTextField();
        jlPesoMinimo = new javax.swing.JLabel();
        jtxPesoMinimo = new javax.swing.JTextField();
        jlPesoMax = new javax.swing.JLabel();
        jtxPesoMax = new javax.swing.JTextField();
        jlExcesso = new javax.swing.JLabel();
        jtxExcesso = new javax.swing.JTextField();
        jlPunho = new javax.swing.JLabel();
        jtxPunho = new javax.swing.JFormattedTextField();
        jlFemur = new javax.swing.JLabel();
        jtxFemur = new javax.swing.JFormattedTextField();
        jbLimparAlunoAvali = new javax.swing.JButton();
        Lampada = new javax.swing.JLabel();
        Warning = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbExcutarCalculo = new javax.swing.JButton();
        jbSalvarAlunoDado = new javax.swing.JButton();
        jbSairAlunoDado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fabrica de Monstros - Cadastro do aluno");

        jlNome.setText("Nome:");

        jtxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNomeActionPerformed(evt);
            }
        });

        grupoSexo.add(jrMasculino);
        jrMasculino.setText("Masculino");
        jrMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMasculinoActionPerformed(evt);
            }
        });

        grupoSexo.add(jrFeminino);
        jrFeminino.setText("Feminino");
        jrFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrFemininoActionPerformed(evt);
            }
        });

        jlRua.setText("Rua: ");

        jtxRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxRuaActionPerformed(evt);
            }
        });

        jlBairro.setText("Bairro: ");

        jlNumero.setText("Número:");

        jlCPF.setText("CPF:");

        try {
            jtxCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtxCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCPFActionPerformed(evt);
            }
        });

        jlCidade.setText("Cidade:");

        jlEstado.setText("Estado:");

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins" }));

        jlHorario.setText("Horário:");

        jcbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manha", "Tarde", "Noite", "Livre" }));

        jbLimparAlunoDado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLimparAlunoDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/limpar.png"))); // NOI18N
        jbLimparAlunoDado.setText("Limpar campos");
        jbLimparAlunoDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparAlunoDadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelAlunoLayout = new javax.swing.GroupLayout(PainelAluno);
        PainelAluno.setLayout(PainelAlunoLayout);
        PainelAlunoLayout.setHorizontalGroup(
            PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlunoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAlunoLayout.createSequentialGroup()
                        .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome)
                            .addComponent(jlCPF))
                        .addGap(18, 18, 18)
                        .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAlunoLayout.createSequentialGroup()
                                .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrFeminino))
                            .addComponent(jtxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxRua, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelAlunoLayout.createSequentialGroup()
                        .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbLimparAlunoDado)
                            .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlRua)
                                .addGroup(PainelAlunoLayout.createSequentialGroup()
                                    .addComponent(jlBairro)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jlNumero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PainelAlunoLayout.createSequentialGroup()
                                    .addComponent(jlHorario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAlunoLayout.createSequentialGroup()
                                .addComponent(jlEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PainelAlunoLayout.createSequentialGroup()
                                .addComponent(jlCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        PainelAlunoLayout.setVerticalGroup(
            PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlunoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelAlunoLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jlNome))
                    .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrMasculino)
                        .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jrFeminino)))
                .addGap(18, 18, 18)
                .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCPF)
                    .addComponent(jtxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRua)
                    .addComponent(jtxRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBairro)
                    .addComponent(jtxBairro)
                    .addComponent(jlNumero)
                    .addComponent(jtxNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCidade)
                    .addComponent(jtxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstado)
                    .addComponent(jcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlHorario)
                    .addComponent(jcbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(jbLimparAlunoDado)
                .addGap(56, 56, 56))
        );

        jTabbedPane1.addTab("Informações do aluno", PainelAluno);

        jlPesoCorporal.setText("Peso corporal: ");

        jtxPesoCorporal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jlEstatura.setText("Estatura:");

        jtxEstatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jlGordura.setText("% de gordura:");

        jlTriceps.setText("Tríceps: ");

        jtxTriceps.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jlSubescapular.setText("Subescapular:");

        jtxSubescapular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jlAbdominal.setText("Abdominal:");

        jtxAbdominal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jlSupra.setText("Supra ilíaca:");

        jtxSupra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jtxSupra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxSupraActionPerformed(evt);
            }
        });

        jtxGordura.setEditable(false);

        jlMusculo.setText("% muscular:");

        jtxMusculo.setEditable(false);

        jlImc.setText("IMC:");

        jtxImc.setEditable(false);
        jtxImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxImcActionPerformed(evt);
            }
        });

        jlPesoMagro.setText("Peso magro:");

        jtxPesoMagro.setEditable(false);

        jlPesoMuscular.setText("Peso muscular:");

        jtxPesoMuscular.setEditable(false);

        jlPesoGordo.setText("Peso gordo:");

        jtxPesoGordo.setEditable(false);

        jlPesoResidual.setText("Peso residual:");

        jtxPesoResidual.setEditable(false);

        jlPesoOsseo.setText("Peso ósseo:");

        jtxPesoOsseo.setEditable(false);

        jlPesoMinimo.setText("Peso mínimo:");

        jtxPesoMinimo.setEditable(false);

        jlPesoMax.setText("Peso máximo:");

        jtxPesoMax.setEditable(false);

        jlExcesso.setText("Excesso de peso:");

        jtxExcesso.setEditable(false);

        jlPunho.setText("Punho:");

        jtxPunho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jlFemur.setText("Fêmur:");

        jtxFemur.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jbLimparAlunoAvali.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbLimparAlunoAvali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/limpar.png"))); // NOI18N
        jbLimparAlunoAvali.setText("Limpar campos");
        jbLimparAlunoAvali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparAlunoAvaliActionPerformed(evt);
            }
        });

        Lampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/alerta.png"))); // NOI18N

        Warning.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Warning.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Atenção: O sistema\nutiliza o Protocolo de\nFaulker para calcular\na % de gordura");
        Warning.setViewportView(jTextArea1);

        jbExcutarCalculo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbExcutarCalculo.setText("Executar Calculo");
        jbExcutarCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcutarCalculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelAvaliacaoLayout = new javax.swing.GroupLayout(PainelAvaliacao);
        PainelAvaliacao.setLayout(PainelAvaliacaoLayout);
        PainelAvaliacaoLayout.setHorizontalGroup(
            PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jlExcesso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxExcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Lampada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jbExcutarCalculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jbLimparAlunoAvali)
                                .addGap(112, 112, 112)))
                        .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlPesoCorporal)
                                    .addComponent(jlSubescapular)
                                    .addComponent(jlPunho))
                                .addGap(18, 18, 18)
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxPesoCorporal, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jtxSubescapular)
                                    .addComponent(jtxPunho))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                        .addComponent(jlFemur)
                                        .addGap(29, 29, 29)
                                        .addComponent(jtxFemur))
                                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                        .addComponent(jlEstatura)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                        .addComponent(jlAbdominal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxAbdominal)))
                                .addGap(18, 18, 18)
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTriceps)
                                    .addComponent(jlSupra))
                                .addGap(18, 18, 18)
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxTriceps, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(jtxSupra)))
                            .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlGordura)
                                    .addComponent(jlPesoMagro)
                                    .addComponent(jlPesoResidual)
                                    .addComponent(jlPesoMax))
                                .addGap(18, 18, 18)
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxGordura)
                                    .addComponent(jtxPesoMagro)
                                    .addComponent(jtxPesoResidual)
                                    .addComponent(jtxPesoMax, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlMusculo)
                                            .addComponent(jlPesoMuscular))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxMusculo)
                                            .addComponent(jtxPesoMuscular, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)))
                                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                        .addComponent(jlPesoOsseo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxPesoOsseo)))
                                .addGap(18, 18, 18)
                                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                        .addComponent(jlImc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                        .addComponent(jtxImc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlPesoGordo)
                                            .addComponent(jlPesoMinimo))
                                        .addGap(18, 18, 18)
                                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxPesoMinimo)
                                            .addComponent(jtxPesoGordo))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PainelAvaliacaoLayout.setVerticalGroup(
            PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesoCorporal)
                    .addComponent(jtxPesoCorporal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEstatura)
                    .addComponent(jtxEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTriceps)
                    .addComponent(jtxTriceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSubescapular)
                    .addComponent(jtxSubescapular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAbdominal)
                    .addComponent(jtxAbdominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSupra)
                    .addComponent(jtxSupra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPunho)
                    .addComponent(jtxPunho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFemur)
                    .addComponent(jtxFemur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGordura)
                    .addComponent(jtxGordura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlMusculo)
                    .addComponent(jtxMusculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlImc)
                    .addComponent(jtxImc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesoMagro)
                    .addComponent(jtxPesoMagro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPesoMuscular)
                    .addComponent(jtxPesoMuscular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPesoGordo)
                    .addComponent(jtxPesoGordo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesoResidual)
                    .addComponent(jtxPesoResidual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPesoOsseo)
                    .addComponent(jtxPesoOsseo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPesoMinimo)
                    .addComponent(jtxPesoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lampada)
                            .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(PainelAvaliacaoLayout.createSequentialGroup()
                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesoMax)
                            .addComponent(jtxPesoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlExcesso)
                            .addComponent(jtxExcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PainelAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbLimparAlunoAvali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbExcutarCalculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );

        jTabbedPane1.addTab("Avaliação", PainelAvaliacao);

        jbSalvarAlunoDado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSalvarAlunoDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/salvar.png"))); // NOI18N
        jbSalvarAlunoDado.setText("Salvar ");
        jbSalvarAlunoDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarAlunoDadoActionPerformed(evt);
            }
        });

        jbSairAlunoDado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbSairAlunoDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/sair.png"))); // NOI18N
        jbSairAlunoDado.setText("Sair ");
        jbSairAlunoDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairAlunoDadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSalvarAlunoDado)
                .addGap(18, 18, 18)
                .addComponent(jbSairAlunoDado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvarAlunoDado)
                    .addComponent(jbSairAlunoDado))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxRuaActionPerformed

    private void jrFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrFemininoActionPerformed

    private void jtxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxNomeActionPerformed

    private void jtxCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCPFActionPerformed

    private void jbSairAlunoDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairAlunoDadoActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Se você sair irá perder todos os dados informados, deseja continuar?")==0){
            dispose();
            AlunoView aluno = new AlunoView();
            aluno.setVisible(true);
        }
        
    }//GEN-LAST:event_jbSairAlunoDadoActionPerformed

    private void jbSalvarAlunoDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarAlunoDadoActionPerformed
        // TODO add your handling code here:
        if (!Editar){
            if((!jtxPesoCorporal.getText().trim().equals("")) && (jrMasculino.isSelected() || jrFeminino.isSelected())){
                CadastroAlunoModel aluno = new CadastroAlunoModel();
                aluno.setNomeAluno(jtxNome.getText());
                if (jrMasculino.isSelected())
                    aluno.setSexoAluno(jrMasculino.getText());
                if (jrFeminino.isSelected())
                    aluno.setSexoAluno(jrFeminino.getText());
                aluno.setCpfAluno(jtxCPF.getText());
                aluno.setRuaAluno(jtxRua.getText());
                aluno.setBairroAluno(jtxBairro.getText());
                aluno.setNumeroAluno(Integer.parseInt(jtxNumero.getText()));
                aluno.setCidadeAluno(jtxCidade.getText());
                aluno.setHorarioAluno((String)jcbHorario.getSelectedItem());
                aluno.setEstadoAluno((String)jcbEstado.getSelectedItem());

                aluno.setPesoCorporal(Float.parseFloat(jtxPesoCorporal.getText()));
                aluno.setEstatura(Float.parseFloat(jtxEstatura.getText()));
                aluno.setTriceps(Float.parseFloat(jtxTriceps.getText()));
                aluno.setSubescapular(Float.parseFloat(jtxSubescapular.getText()));
                aluno.setAbdominal(Float.parseFloat(jtxAbdominal.getText()));
                aluno.setSupra(Float.parseFloat(jtxSupra.getText()));
                aluno.setPunho(Float.parseFloat(jtxPunho.getText()));
                aluno.setFemur(Float.parseFloat(jtxFemur.getText()));
                aluno.setGordura(Float.parseFloat(jtxGordura.getText()));
                aluno.setMuscular(Float.parseFloat(jtxMusculo.getText()));
                aluno.setImc(Float.parseFloat(jtxImc.getText()));
                aluno.setPesoMagro(Float.parseFloat(jtxPesoMagro.getText()));
                aluno.setPesoMuscular(Float.parseFloat(jtxPesoMuscular.getText()));
                aluno.setPesoGordo(Float.parseFloat(jtxPesoGordo.getText()));
                aluno.setPesoResidual(Float.parseFloat(jtxPesoResidual.getText()));
                aluno.setPesoOsseo(Float.parseFloat(jtxPesoOsseo.getText()));
                aluno.setPesoMinimo(Float.parseFloat(jtxPesoMinimo.getText()));
                aluno.setPesoMaximo(Float.parseFloat(jtxPesoMax.getText()));
                aluno.setExcesso(Float.parseFloat(jtxExcesso.getText()));

                AlunoController controle = new AlunoController();
                if(controle.inserirAluno(aluno)){
                    JOptionPane.showMessageDialog(this, "Aluno Cadastrado com sucesso!");
                    jbLimparAlunoDadoActionPerformed(evt);
                    jbLimparAlunoAvaliActionPerformed(evt);
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Aluno!", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
                }
           }else{
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Aluno! Campos Incompletos", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            if((!jtxPesoCorporal.getText().trim().equals(""))&& (jrMasculino.isSelected() || jrFeminino.isSelected())){
                CadastroAlunoModel aluno = new CadastroAlunoModel();
                aluno.setCodigoAluno(CodigoEditAluno);
                aluno.setNomeAluno(jtxNome.getText());
                if (jrMasculino.isSelected())
                    aluno.setSexoAluno(jrMasculino.getText());
                if (jrFeminino.isSelected())
                    aluno.setSexoAluno(jrFeminino.getText());
                aluno.setCpfAluno(jtxCPF.getText());
                aluno.setRuaAluno(jtxRua.getText());
                aluno.setBairroAluno(jtxBairro.getText());
                aluno.setNumeroAluno(Integer.parseInt(jtxNumero.getText()));
                aluno.setCidadeAluno(jtxCidade.getText());
                aluno.setHorarioAluno((String)jcbHorario.getSelectedItem());
                aluno.setEstadoAluno((String)jcbEstado.getSelectedItem());

                aluno.setPesoCorporal(Float.parseFloat(jtxPesoCorporal.getText()));
                aluno.setEstatura(Float.parseFloat(jtxEstatura.getText()));
                aluno.setTriceps(Float.parseFloat(jtxTriceps.getText()));
                aluno.setSubescapular(Float.parseFloat(jtxSubescapular.getText()));
                aluno.setAbdominal(Float.parseFloat(jtxAbdominal.getText()));
                aluno.setSupra(Float.parseFloat(jtxSupra.getText()));
                aluno.setPunho(Float.parseFloat(jtxPunho.getText()));
                aluno.setFemur(Float.parseFloat(jtxFemur.getText()));
                aluno.setGordura(Float.parseFloat(jtxGordura.getText()));
                aluno.setMuscular(Float.parseFloat(jtxMusculo.getText()));
                aluno.setImc(Float.parseFloat(jtxImc.getText()));
                aluno.setPesoMagro(Float.parseFloat(jtxPesoMagro.getText()));
                aluno.setPesoMuscular(Float.parseFloat(jtxPesoMuscular.getText()));
                aluno.setPesoGordo(Float.parseFloat(jtxPesoGordo.getText()));
                aluno.setPesoResidual(Float.parseFloat(jtxPesoResidual.getText()));
                aluno.setPesoOsseo(Float.parseFloat(jtxPesoOsseo.getText()));
                aluno.setPesoMinimo(Float.parseFloat(jtxPesoMinimo.getText()));
                aluno.setPesoMaximo(Float.parseFloat(jtxPesoMax.getText()));
                aluno.setExcesso(Float.parseFloat(jtxExcesso.getText()));
                
                AlunoController controle = new AlunoController();
                if(controle.editarAluno(aluno)){
                    JOptionPane.showMessageDialog(this, "Aluno Editado com sucesso!");
                }else{
                    JOptionPane.showMessageDialog(this, "Erro ao Editar Aluno!", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
                }       
           }else{
                JOptionPane.showMessageDialog(this, "Erro ao Cadastrar Aluno! Campos Incompletos", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
            }
            dispose();
            AlunoView aluno = new AlunoView();
            aluno.setVisible(true);
            Editar = false;
            CodigoEditAluno = 0;
        }
            
    }//GEN-LAST:event_jbSalvarAlunoDadoActionPerformed

    private void jtxImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxImcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxImcActionPerformed

    private void jbLimparAlunoDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparAlunoDadoActionPerformed
        // TODO add your handling code here:
        jtxNome.setText("");
        grupoSexo.clearSelection();
        jtxCPF.setText("");
        jtxRua.setText("");
        jtxBairro.setText("");
        jtxNumero.setText("");
        jtxCidade.setText("");
    }//GEN-LAST:event_jbLimparAlunoDadoActionPerformed

    private void jbLimparAlunoAvaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparAlunoAvaliActionPerformed
        // TODO add your handling code here:
        jtxPesoCorporal.setText("");
        jtxEstatura.setText("");
        jtxTriceps.setText("");
        jtxSubescapular.setText("");
        jtxAbdominal.setText("");
        jtxSupra.setText("");
        jtxPunho.setText("");
        jtxFemur.setText("");
        jtxGordura.setText("");
        jtxMusculo.setText("");
        jtxImc.setText("");
        jtxPesoMagro.setText("");
        jtxPesoMuscular.setText("");
        jtxPesoGordo.setText("");
        jtxPesoResidual.setText("");
        jtxPesoOsseo.setText("");
        jtxPesoMinimo.setText("");
        jtxPesoMax.setText("");
        jtxExcesso.setText("");
    
    }//GEN-LAST:event_jbLimparAlunoAvaliActionPerformed

    private void jrMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrMasculinoActionPerformed

    private void jbExcutarCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcutarCalculoActionPerformed
        // TODO add your handling code here:
        if((!jtxPesoCorporal.getText().trim().equals("")) && (!jtxEstatura.getText().trim().equals(""))
                && (!jtxTriceps.getText().trim().equals("")) && (!jtxSubescapular.getText().trim().equals(""))
                && (!jtxAbdominal.getText().trim().equals("")) && (!jtxSupra.getText().trim().equals(""))
                && (!jtxPunho.getText().trim().equals("")) && (!jtxFemur.getText().trim().equals(""))){
            float gordura = (float) ((Float.parseFloat(jtxTriceps.getText()) 
                    + Float.parseFloat(jtxSubescapular.getText())
                    + Float.parseFloat(jtxSupra.getText())
                    + Float.parseFloat(jtxAbdominal.getText())) * (0.153 + (5.783/100)));
            jtxGordura.setText(String.valueOf(gordura));
            
            float Imc = (float) (Float.parseFloat(jtxPesoCorporal.getText())
                    /(Float.parseFloat(jtxEstatura.getText())* Float.parseFloat(jtxEstatura.getText())));
            jtxImc.setText(String.valueOf(Imc));
            
            float pesoGordo = Float.parseFloat(jtxPesoCorporal.getText()) * gordura;
            jtxPesoGordo.setText(String.valueOf(pesoGordo));
            
            float pesoMagro = Float.parseFloat(jtxPesoCorporal.getText()) - pesoGordo;
            jtxPesoMagro.setText(String.valueOf(pesoMagro));
            
            float pesoOsseo = (float) (Float.parseFloat(jtxEstatura.getText())*Float.parseFloat(jtxEstatura.getText()))
                    * (Float.parseFloat(jtxPunho.getText())/100) 
                    * (Float.parseFloat(jtxFemur.getText())/100) * 400;
            jtxPesoOsseo.setText(String.valueOf(pesoOsseo));
            
            float pesoResidual = (float) (Float.parseFloat(jtxPesoCorporal.getText()) * 0.24);
            jtxPesoResidual.setText(String.valueOf(pesoResidual));
            
            float pesoMuscular = (Float.parseFloat(jtxPesoCorporal.getText())
                    - (pesoGordo + pesoOsseo + pesoResidual));
            jtxPesoMuscular.setText(String.valueOf(pesoMuscular));
            
            float pesoMinimo = (float) (pesoMagro/0.91);
            jtxPesoMinimo.setText(String.valueOf(pesoMinimo));
            
            float pesoMaximo = (float) (pesoGordo/0.895);
            jtxPesoMax.setText(String.valueOf(pesoMaximo));
            
            float excesso = Float.parseFloat(jtxPesoCorporal.getText()) - pesoMinimo;
            jtxExcesso.setText(String.valueOf(excesso));
            
            float musculo = pesoMuscular/Float.parseFloat(jtxPesoCorporal.getText());
            jtxMusculo.setText(String.valueOf(musculo));
        }else{
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", 
                        "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcutarCalculoActionPerformed

    private void jtxSupraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxSupraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxSupraActionPerformed

    /**
     * @param args the command line arguments
     */
    
    void recebeDados(int CodigoAluno, boolean EditarAluno){
        CodigoEditAluno = CodigoAluno;
        Editar = EditarAluno;
        CadastroAlunoModel aluno = new CadastroAlunoModel();
        aluno.setCodigoAluno(CodigoEditAluno);
        AlunoController controle = new AlunoController();
        aluno = controle.selecionarAluno(aluno);
        if(aluno != null){
            jtxNome.setText(aluno.getNomeAluno());
            jtxCPF.setText(aluno.getCpfAluno());
            jtxRua.setText(aluno.getRuaAluno());
            jtxBairro.setText(aluno.getBairroAluno());
            jtxNumero.setText(String.valueOf(aluno.getNumeroAluno()));
            jtxCidade.setText(aluno.getCidadeAluno());    
            jtxPesoCorporal.setText(String.valueOf(aluno.getPesoCorporal()));
            jtxEstatura.setText(String.valueOf(aluno.getEstatura()));
            jtxTriceps.setText(String.valueOf(aluno.getTriceps()));
            jtxSubescapular.setText(String.valueOf(aluno.getSubescapular()));
            jtxAbdominal.setText(String.valueOf(aluno.getAbdominal()));
            jtxSupra.setText(String.valueOf(aluno.getSupra()));
            jtxPunho.setText(String.valueOf(aluno.getPunho()));
            jtxFemur.setText(String.valueOf(aluno.getFemur()));
            jtxGordura.setText(String.valueOf(aluno.getGordura()));
            jtxMusculo.setText(String.valueOf(aluno.getMuscular()));
            jtxImc.setText(String.valueOf(aluno.getImc()));
            jtxPesoMagro.setText(String.valueOf(aluno.getPesoMagro()));
            jtxPesoMuscular.setText(String.valueOf(aluno.getPesoMuscular()));
            jtxPesoGordo.setText(String.valueOf(aluno.getPesoGordo()));
            jtxPesoResidual.setText(String.valueOf(aluno.getPesoResidual()));
            jtxPesoOsseo.setText(String.valueOf(aluno.getPesoOsseo()));
            jtxPesoMinimo.setText(String.valueOf(aluno.getPesoMinimo()));
            jtxPesoMax.setText(String.valueOf(aluno.getPesoMaximo()));
            jtxExcesso.setText(String.valueOf(aluno.getExcesso()));
        }else{
            JOptionPane.showMessageDialog(this, "Aluno não encontrado!", 
                        "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lampada;
    private javax.swing.JPanel PainelAluno;
    private javax.swing.JPanel PainelAvaliacao;
    private javax.swing.JScrollPane Warning;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbExcutarCalculo;
    private javax.swing.JButton jbLimparAlunoAvali;
    private javax.swing.JButton jbLimparAlunoDado;
    private javax.swing.JButton jbSairAlunoDado;
    private javax.swing.JButton jbSalvarAlunoDado;
    private javax.swing.JComboBox<String> jcbEstado;
    private javax.swing.JComboBox<String> jcbHorario;
    private javax.swing.JLabel jlAbdominal;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCPF;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlEstatura;
    private javax.swing.JLabel jlExcesso;
    private javax.swing.JLabel jlFemur;
    private javax.swing.JLabel jlGordura;
    private javax.swing.JLabel jlHorario;
    private javax.swing.JLabel jlImc;
    private javax.swing.JLabel jlMusculo;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlPesoCorporal;
    private javax.swing.JLabel jlPesoGordo;
    private javax.swing.JLabel jlPesoMagro;
    private javax.swing.JLabel jlPesoMax;
    private javax.swing.JLabel jlPesoMinimo;
    private javax.swing.JLabel jlPesoMuscular;
    private javax.swing.JLabel jlPesoOsseo;
    private javax.swing.JLabel jlPesoResidual;
    private javax.swing.JLabel jlPunho;
    private javax.swing.JLabel jlRua;
    private javax.swing.JLabel jlSubescapular;
    private javax.swing.JLabel jlSupra;
    private javax.swing.JLabel jlTriceps;
    private javax.swing.JRadioButton jrFeminino;
    private javax.swing.JRadioButton jrMasculino;
    private javax.swing.JFormattedTextField jtxAbdominal;
    private javax.swing.JTextField jtxBairro;
    private javax.swing.JFormattedTextField jtxCPF;
    private javax.swing.JTextField jtxCidade;
    private javax.swing.JFormattedTextField jtxEstatura;
    private javax.swing.JTextField jtxExcesso;
    private javax.swing.JFormattedTextField jtxFemur;
    private javax.swing.JTextField jtxGordura;
    private javax.swing.JTextField jtxImc;
    private javax.swing.JTextField jtxMusculo;
    private javax.swing.JTextField jtxNome;
    private javax.swing.JTextField jtxNumero;
    private javax.swing.JFormattedTextField jtxPesoCorporal;
    private javax.swing.JTextField jtxPesoGordo;
    private javax.swing.JTextField jtxPesoMagro;
    private javax.swing.JTextField jtxPesoMax;
    private javax.swing.JTextField jtxPesoMinimo;
    private javax.swing.JTextField jtxPesoMuscular;
    private javax.swing.JTextField jtxPesoOsseo;
    private javax.swing.JTextField jtxPesoResidual;
    private javax.swing.JFormattedTextField jtxPunho;
    private javax.swing.JTextField jtxRua;
    private javax.swing.JFormattedTextField jtxSubescapular;
    private javax.swing.JFormattedTextField jtxSupra;
    private javax.swing.JFormattedTextField jtxTriceps;
    // End of variables declaration//GEN-END:variables

}
