/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EquipamentoController;
import Model.CadastroEquipamentoModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tylui
 */
public class EquipamentosView extends javax.swing.JFrame {

    /**
     * Creates new form EquipamentosView
     */
    private static int id = 1;
    private int linha = 0;
    private int CodigoEdit = 0;
    private boolean Editar = true;
    
    public EquipamentosView() {
        initComponents();
        jbEditarEquipamento.setEnabled(false);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lampada = new javax.swing.JLabel();
        jbCancelarEquipamento = new javax.swing.JButton();
        PainelPesquisa = new javax.swing.JPanel();
        jtxPesquisaEquipamento = new javax.swing.JTextField();
        jbPesquisarEquipamento = new javax.swing.JButton();
        Painel2 = new javax.swing.JPanel();
        jbEditarEquipamento = new javax.swing.JButton();
        jbNovoEquipamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaEquipamento = new javax.swing.JTable();
        Warning = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenu = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiAluno = new javax.swing.JMenuItem();
        jmiInstrutores = new javax.swing.JMenuItem();
        jmiTreinos = new javax.swing.JMenuItem();
        jmiEquipamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fabrica de Monstros - Dados dos equipamentos");
        setResizable(false);

        Lampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/alerta.png"))); // NOI18N

        jbCancelarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/cancelar.png"))); // NOI18N
        jbCancelarEquipamento.setText("Cancelar ");
        jbCancelarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarEquipamentoActionPerformed(evt);
            }
        });

        PainelPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        PainelPesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPesquisarEquipamento.setText("Pesquisar");
        jbPesquisarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarEquipamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPesquisaLayout = new javax.swing.GroupLayout(PainelPesquisa);
        PainelPesquisa.setLayout(PainelPesquisaLayout);
        PainelPesquisaLayout.setHorizontalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxPesquisaEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarEquipamento))
        );
        PainelPesquisaLayout.setVerticalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxPesquisaEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarEquipamento))
                .addContainerGap())
        );

        javax.swing.GroupLayout Painel2Layout = new javax.swing.GroupLayout(Painel2);
        Painel2.setLayout(Painel2Layout);
        Painel2Layout.setHorizontalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Painel2Layout.setVerticalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jbEditarEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbEditarEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/editar.png"))); // NOI18N
        jbEditarEquipamento.setText("Editar ");
        jbEditarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarEquipamentoActionPerformed(evt);
            }
        });

        jbNovoEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbNovoEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/novo.png"))); // NOI18N
        jbNovoEquipamento.setText("Novo ");
        jbNovoEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoEquipamentoActionPerformed(evt);
            }
        });

        TabelaEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Marca", "Modelo", "Peso limite", "Tipo de uso", "Danificado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaEquipamento.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TabelaEquipamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaEquipamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaEquipamento);

        Warning.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Warning.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Voce no momento esta \nno cadastro dos\nequipamentos");
        Warning.setViewportView(jTextArea1);

        jmCadastro.setText("Cadastro");

        jmiAluno.setText("Alunos");
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiAluno);

        jmiInstrutores.setText("Instrutores");
        jmiInstrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInstrutoresActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiInstrutores);

        jmiTreinos.setText("Treinos");
        jmiTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTreinosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiTreinos);

        jmiEquipamentos.setText("Equipamentos");
        jmiEquipamentos.setEnabled(false);
        jmCadastro.add(jmiEquipamentos);

        jMenu.add(jmCadastro);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNovoEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditarEquipamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelarEquipamento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lampada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PainelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lampada)
                                    .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbNovoEquipamento)
                            .addComponent(jbEditarEquipamento)
                            .addComponent(jbCancelarEquipamento)))
                    .addComponent(Painel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
        // TODO add your handling code here:
        AlunoView aluno = new AlunoView();
        aluno.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiAlunoActionPerformed

    private void jbCancelarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarEquipamentoActionPerformed
        // TODO add your handling code here:
        dispose();
        Principal inicio = new Principal();
        inicio.setVisible(true);
    }//GEN-LAST:event_jbCancelarEquipamentoActionPerformed

    private void jmiInstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstrutoresActionPerformed
        // TODO add your handling code here:
        InstrutoresView instrutores = new InstrutoresView();
        instrutores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiInstrutoresActionPerformed

    private void jmiTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTreinosActionPerformed
        // TODO add your handling code here:
        TreinoView treino = new TreinoView();
        treino.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiTreinosActionPerformed

    private void jbNovoEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoEquipamentoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroEquipamento newEquipamento = new CadastroEquipamento();
        newEquipamento.setVisible(true);
    }//GEN-LAST:event_jbNovoEquipamentoActionPerformed

    private void TabelaEquipamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaEquipamentoMouseClicked
        // TODO add your handling code here:
        linha = TabelaEquipamento.getSelectedRow();
        jbEditarEquipamento.setEnabled(true);
        CodigoEdit = Integer.parseInt((String)TabelaEquipamento.getValueAt(linha, 0));
    }//GEN-LAST:event_TabelaEquipamentoMouseClicked

    private void jbEditarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarEquipamentoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroEquipamento editeEquipamento = new CadastroEquipamento();
        editeEquipamento.setVisible(true);
        editeEquipamento.recebeDados(CodigoEdit, Editar);
    }//GEN-LAST:event_jbEditarEquipamentoActionPerformed

    private void jbPesquisarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarEquipamentoActionPerformed
        // TODO add your handling code here:
        if (!jtxPesquisaEquipamento.getText().trim().equals("")){
            CadastroEquipamentoModel equipamento = new CadastroEquipamentoModel();
            equipamento.setTipoEquipamento(jtxPesquisaEquipamento.getText());
            EquipamentoController controller = new EquipamentoController();
            ArrayList<CadastroEquipamentoModel> lista = controller.selecionarTodosTiposEquipamentos(equipamento);
            if(!lista.isEmpty()){
                DefaultTableModel modelo = (DefaultTableModel)TabelaEquipamento.getModel();
                modelo.setRowCount(0);
                for(CadastroEquipamentoModel e: lista){
                    modelo.addRow(new String[]{
                        String.valueOf(e.getCodigoEquipamento()),
                        e.getDescricaoEquipamento(),
                        e.getMarcaEquipamento(),
                        e.getModeloEquipamento(),
                        e.getPesoEquipamento(),
                        e.getTipoEquipamento(),
                        e.getDanificadoEquipamento()
                    });
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Pesquisar", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbPesquisarEquipamentoActionPerformed

    /**
     * @param args the command line arguments
     */

    public void atualizarTabela(){
        EquipamentoController equipamento = new EquipamentoController();
        ArrayList<CadastroEquipamentoModel> lista = equipamento.selecionarTodosEquipamentos();
        if(!lista.isEmpty()){
            DefaultTableModel modelo = (DefaultTableModel)TabelaEquipamento.getModel();
            modelo.setRowCount(0);
            for(CadastroEquipamentoModel e: lista){
                modelo.addRow(new String[]{
                    String.valueOf(e.getCodigoEquipamento()),
                    e.getDescricaoEquipamento(),
                    e.getMarcaEquipamento(),
                    e.getModeloEquipamento(),
                    e.getPesoEquipamento(),
                    e.getTipoEquipamento(),
                    e.getDanificadoEquipamento()
                });
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lampada;
    private javax.swing.JPanel Painel2;
    private javax.swing.JPanel PainelPesquisa;
    private javax.swing.JTable TabelaEquipamento;
    private javax.swing.JScrollPane Warning;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbCancelarEquipamento;
    private javax.swing.JButton jbEditarEquipamento;
    private javax.swing.JButton jbNovoEquipamento;
    private javax.swing.JButton jbPesquisarEquipamento;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiEquipamentos;
    private javax.swing.JMenuItem jmiInstrutores;
    private javax.swing.JMenuItem jmiTreinos;
    private javax.swing.JTextField jtxPesquisaEquipamento;
    // End of variables declaration//GEN-END:variables
}
