/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;



import java.awt.HeadlessException;
import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import util.Conexao;

/**
 *
 * @author tylui
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelbotao = new javax.swing.JPanel();
        jbAlunos = new javax.swing.JButton();
        jbInstrutores = new javax.swing.JButton();
        jbTreino = new javax.swing.JButton();
        jbEquipamento = new javax.swing.JButton();
        Painel1 = new javax.swing.JPanel();
        jlLogo = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiAluno = new javax.swing.JMenuItem();
        jmiInstrutores = new javax.swing.JMenuItem();
        jmiTreinos = new javax.swing.JMenuItem();
        jmiEquipamentos = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jmiRelatorioAluno = new javax.swing.JMenuItem();
        jmiRelatorioEquip = new javax.swing.JMenuItem();
        jmiRelatorioInstrutor = new javax.swing.JMenuItem();
        jmiRelatorioTreino = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fabrica de Monstros");
        setMaximizedBounds(getMaximizedBounds());

        jbAlunos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/aluno.png"))); // NOI18N
        jbAlunos.setText("Alunos ");
        jbAlunos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlunosActionPerformed(evt);
            }
        });
        painelbotao.add(jbAlunos);

        jbInstrutores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbInstrutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/instrutores.png"))); // NOI18N
        jbInstrutores.setText("Instrutores ");
        jbInstrutores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbInstrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInstrutoresActionPerformed(evt);
            }
        });
        painelbotao.add(jbInstrutores);

        jbTreino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/treino.png"))); // NOI18N
        jbTreino.setText("Treinos ");
        jbTreino.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTreinoActionPerformed(evt);
            }
        });
        painelbotao.add(jbTreino);

        jbEquipamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbEquipamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/iconfinder-sports-and-competitionwellnessfitnessweighingweightliftingsportivebarbellsportsexercisegym-4394766_119492.png"))); // NOI18N
        jbEquipamento.setText("Equipamentos ");
        jbEquipamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentoActionPerformed(evt);
            }
        });
        painelbotao.add(jbEquipamento);

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logo.png"))); // NOI18N

        javax.swing.GroupLayout Painel1Layout = new javax.swing.GroupLayout(Painel1);
        Painel1.setLayout(Painel1Layout);
        Painel1Layout.setHorizontalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogo)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Painel1Layout.setVerticalGroup(
            Painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jmCadastro.setText("Cadastro");

        jmiAluno.setText("Alunos");
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiAluno);

        jmiInstrutores.setText("Instrutores");
        jmiInstrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInstrutoresActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiInstrutores);

        jmiTreinos.setText("Treinos");
        jmiTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTreinosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiTreinos);

        jmiEquipamentos.setText("Equipamentos");
        jmiEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEquipamentosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiEquipamentos);

        jMenu.add(jmCadastro);

        jmRelatorio.setText("Relatórios");

        jmiRelatorioAluno.setText("Alunos Cadastrados");
        jmiRelatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioAlunoActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiRelatorioAluno);

        jmiRelatorioEquip.setText("Equipamentos Cadastrados");
        jmiRelatorioEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioEquipActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiRelatorioEquip);

        jmiRelatorioInstrutor.setText("Instrutores Cadastrados");
        jmiRelatorioInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioInstrutorActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiRelatorioInstrutor);

        jmiRelatorioTreino.setText("Treinos Cadastrados");
        jmiRelatorioTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRelatorioTreinoActionPerformed(evt);
            }
        });
        jmRelatorio.add(jmiRelatorioTreino);

        jMenu.add(jmRelatorio);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelbotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelbotao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentoActionPerformed
        // TODO add your handling code here:
        EquipamentosView equipamentos = new EquipamentosView();
        equipamentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbEquipamentoActionPerformed

    private void jbAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlunosActionPerformed
        // TODO add your handling code here:
        AlunoView aluno = new AlunoView();
        aluno.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbAlunosActionPerformed

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
        // TODO add your handling code here:
        AlunoView aluno = new AlunoView();
        aluno.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiAlunoActionPerformed

    private void jmiInstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstrutoresActionPerformed
        // TODO add your handling code here:
        InstrutoresView instrutores =  new InstrutoresView();
        instrutores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiInstrutoresActionPerformed

    private void jbInstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInstrutoresActionPerformed
        // TODO add your handling code here:
        InstrutoresView instrutores =  new InstrutoresView();
        instrutores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbInstrutoresActionPerformed

    private void jmiEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEquipamentosActionPerformed
        // TODO add your handling code here:
        EquipamentosView equipamentos = new EquipamentosView();
        equipamentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiEquipamentosActionPerformed

    private void jmiTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTreinosActionPerformed
        // TODO add your handling code here:
        TreinoView treino = new TreinoView();
        treino.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiTreinosActionPerformed

    private void jbTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTreinoActionPerformed
        // TODO add your handling code here:
        TreinoView treino = new TreinoView();
        treino.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbTreinoActionPerformed

    private void jmiRelatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioAlunoActionPerformed
        // TODO add your handling code here:
        Conexao conexao = new Conexao();
        Map parametros = new HashMap();
        String cidadeAluno = "";
        String src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioAluno.jasper";
        JasperPrint impressao = null;
        if(JOptionPane.showConfirmDialog(this, "Voce deseja gerar o relatório com Filtro?")==0){
            cidadeAluno = (JOptionPane.showInputDialog("Digite a cidade do Aluno"));
        }
        if (!cidadeAluno.equals("")){
            parametros.put("parametrocidade",cidadeAluno);
            src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioAlunoFiltro.jasper";
        }   
        try {
            impressao = JasperFillManager.fillReport(src, parametros , conexao.con);
            JasperViewer viewer = new JasperViewer(impressao, false );
            viewer.setVisible(true);
            viewer.toFront();
            //JasperExportManager.exportReportToPdfFile(impressao, "RELATORIO.pdf");
            //JasperViewer.viewReport(impressao, true); 
            //JOptionPane.showMessageDialog(null, "Exportado");
        } catch (JRException ex) {
            System.out.println("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_jmiRelatorioAlunoActionPerformed

    private void jmiRelatorioEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioEquipActionPerformed
        // TODO add your handling code here:
        Conexao conexao = new Conexao();
        Map parametros = new HashMap();
        String marcaEqui = "";
        String src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioEquipamentos.jasper";
        JasperPrint impressao = null;
        if(JOptionPane.showConfirmDialog(this, "Voce deseja gerar o relatório com Filtro?")==0){
            marcaEqui = (JOptionPane.showInputDialog("Digite a marca do Equipamento"));
        }
        if (!marcaEqui.trim().equals("")){
            parametros.put("parametromarca",marcaEqui);
            src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioEquipamentosFiltro.jasper";
        }  
        try {  
            impressao = JasperFillManager.fillReport(src, parametros, conexao.con );
            JasperViewer viewer = new JasperViewer( impressao , false );
            viewer.setVisible(true);
            viewer.toFront();
            //JasperExportManager.exportReportToPdfFile(impressao, "RELATORIO.pdf");
            //JasperViewer.viewReport(impressao, true); 
            //JOptionPane.showMessageDialog(null, "Exportado"); 
        } catch (JRException ex) {
            System.out.println("Erro: " + ex.getMessage());
        } 
    }//GEN-LAST:event_jmiRelatorioEquipActionPerformed

    private void jmiRelatorioInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioInstrutorActionPerformed
        // TODO add your handling code here:
        Conexao conexao = new Conexao();
        Map parametros = new HashMap();
        String cidadeInstrutor = "";
        String src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioInstrutor.jasper";
        JasperPrint impressao = null;
        if(JOptionPane.showConfirmDialog(this, "Voce deseja gerar o relatório com Filtro?")==0){
            cidadeInstrutor = (JOptionPane.showInputDialog("Digite a cidade do Instruto")); 
        }
        if (!cidadeInstrutor.trim().equals("")){
            parametros.put("parametrocidade",cidadeInstrutor);
            src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioInstrutorFiltro.jasper";
        } 
        try {  
            impressao = JasperFillManager.fillReport(src, parametros, conexao.con );
            JasperViewer viewer = new JasperViewer( impressao , false );
            viewer.setVisible(true);
            viewer.toFront();
            //JasperExportManager.exportReportToPdfFile(impressao, "RELATORIO.pdf");
            //JasperViewer.viewReport(impressao, true); 
            //JOptionPane.showMessageDialog(null, "Exportado"); 
        } catch (JRException ex) {
            System.out.println("Erro: " + ex.getMessage());
        } 
    }//GEN-LAST:event_jmiRelatorioInstrutorActionPerformed

    private void jmiRelatorioTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRelatorioTreinoActionPerformed
        // TODO add your handling code here:
        Conexao conexao = new Conexao();
        Map parametros = new HashMap();
        int codigoAluno = 0;
        String src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioTreino.jasper";
        JasperPrint impressao = null;
        if(JOptionPane.showConfirmDialog(this, "Voce deseja gerar o relatório com Filtro?")==0){
            codigoAluno = Integer.parseInt((JOptionPane.showInputDialog("Digite o Código do Aluno")));
        }
        if (codigoAluno != 0){
            src = "C:\\Users\\Kylsen.Zero\\Documents\\NetBeans\\ProjetoAcademia\\Relatorios\\RelatorioTreinoFiltro.jasper";
            parametros.put("parametrocodigo",codigoAluno);
        }
        try {  
            impressao = JasperFillManager.fillReport(src, parametros, conexao.con );
            JasperViewer viewer = new JasperViewer( impressao , false );
            viewer.setVisible(true);
            viewer.toFront();
            //JasperExportManager.exportReportToPdfFile(impressao, "RELATORIO.pdf");
            //JasperViewer.viewReport(impressao, true); 
            //JOptionPane.showMessageDialog(null, "Exportado"); 
        } catch (JRException ex) {
            System.out.println("Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_jmiRelatorioTreinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JButton jbAlunos;
    private javax.swing.JButton jbEquipamento;
    private javax.swing.JButton jbInstrutores;
    private javax.swing.JButton jbTreino;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmRelatorio;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiEquipamentos;
    private javax.swing.JMenuItem jmiInstrutores;
    private javax.swing.JMenuItem jmiRelatorioAluno;
    private javax.swing.JMenuItem jmiRelatorioEquip;
    private javax.swing.JMenuItem jmiRelatorioInstrutor;
    private javax.swing.JMenuItem jmiRelatorioTreino;
    private javax.swing.JMenuItem jmiTreinos;
    private javax.swing.JPanel painelbotao;
    // End of variables declaration//GEN-END:variables
}
