/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TreinoController;
import Model.CadastroTreinoModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tylui
 */
public class TreinoView extends javax.swing.JFrame {

    /**
     * Creates new form TreinoView
     */
    private static int id = 1;
    private int linha = 0;
    private int CodigoEdit = 0;
    private boolean Editar = true;
    
    public TreinoView() {
        initComponents();
        jbEditarTreino.setEnabled(false);
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PainelPesquisa = new javax.swing.JPanel();
        jtxPesquisaTreino = new javax.swing.JTextField();
        jbPesquisarTreino = new javax.swing.JButton();
        jbCancelarTreino = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaTreino = new javax.swing.JTable();
        Painel2 = new javax.swing.JPanel();
        jbEditarTreino = new javax.swing.JButton();
        Warning = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Lampada = new javax.swing.JLabel();
        jbNovoTreino = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiAluno = new javax.swing.JMenuItem();
        jmiInstrutores = new javax.swing.JMenuItem();
        jmiTreinos = new javax.swing.JMenuItem();
        jmiEquipamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fabrica de Monstros - Dados dos treinos");
        setResizable(false);

        PainelPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        PainelPesquisa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPesquisarTreino.setText("Pesquisar");
        jbPesquisarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarTreinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPesquisaLayout = new javax.swing.GroupLayout(PainelPesquisa);
        PainelPesquisa.setLayout(PainelPesquisaLayout);
        PainelPesquisaLayout.setHorizontalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxPesquisaTreino, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisarTreino))
        );
        PainelPesquisaLayout.setVerticalGroup(
            PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxPesquisaTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarTreino))
                .addContainerGap())
        );

        jbCancelarTreino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbCancelarTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/cancelar.png"))); // NOI18N
        jbCancelarTreino.setText("Cancelar ");
        jbCancelarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarTreinoActionPerformed(evt);
            }
        });

        TabelaTreino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Aluno", "Nome Aluno", "Código", "Modalidade", "Descrição", "Duração", "Esforço(%)", "Frequência Cardíaca Média", "Gasto Calórico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaTreino.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TabelaTreino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaTreinoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaTreino);

        javax.swing.GroupLayout Painel2Layout = new javax.swing.GroupLayout(Painel2);
        Painel2.setLayout(Painel2Layout);
        Painel2Layout.setHorizontalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Painel2Layout.setVerticalGroup(
            Painel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jbEditarTreino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbEditarTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/editar.png"))); // NOI18N
        jbEditarTreino.setText("Editar ");
        jbEditarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarTreinoActionPerformed(evt);
            }
        });

        Warning.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Warning.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Voce no momento esta \nno cadastro dos treinos");
        Warning.setViewportView(jTextArea1);

        Lampada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/alerta.png"))); // NOI18N

        jbNovoTreino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbNovoTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/novo.png"))); // NOI18N
        jbNovoTreino.setText("Novo ");
        jbNovoTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoTreinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNovoTreino)
                        .addGap(18, 18, 18)
                        .addComponent(jbEditarTreino)
                        .addGap(29, 29, 29)
                        .addComponent(jbCancelarTreino))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Lampada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22)
                .addComponent(Painel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Painel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PainelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lampada)
                                    .addComponent(Warning, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbEditarTreino)
                            .addComponent(jbCancelarTreino)
                            .addComponent(jbNovoTreino)))))
        );

        jmCadastro.setText("Cadastro");

        jmiAluno.setText("Alunos");
        jmiAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlunoActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiAluno);

        jmiInstrutores.setText("Instrutores");
        jmiInstrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInstrutoresActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiInstrutores);

        jmiTreinos.setText("Treinos");
        jmiTreinos.setEnabled(false);
        jmiTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTreinosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiTreinos);

        jmiEquipamentos.setText("Equipamentos");
        jmiEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEquipamentosActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiEquipamentos);

        jMenu.add(jmCadastro);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlunoActionPerformed
        // TODO add your handling code here:
        AlunoView aluno = new AlunoView();
        aluno.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiAlunoActionPerformed

    private void jmiTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTreinosActionPerformed
        // TODO add your handling code here:
        TreinoView treino = new TreinoView();
        treino.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiTreinosActionPerformed

    private void jmiEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEquipamentosActionPerformed
        // TODO add your handling code here:
        EquipamentosView equipamentos = new EquipamentosView();
        equipamentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiEquipamentosActionPerformed

    private void jmiInstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInstrutoresActionPerformed
        // TODO add your handling code here:
        InstrutoresView instrutores = new InstrutoresView();
        instrutores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmiInstrutoresActionPerformed

    private void jbCancelarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarTreinoActionPerformed
        // TODO add your handling code here:
        dispose();
        Principal inicio = new Principal();
        inicio.setVisible(true);
    }//GEN-LAST:event_jbCancelarTreinoActionPerformed

    private void jbEditarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarTreinoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroTreino editeTreino = new CadastroTreino();
        editeTreino.setVisible(true);
        editeTreino.recebeDados(CodigoEdit, Editar);
    }//GEN-LAST:event_jbEditarTreinoActionPerformed

    private void jbNovoTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoTreinoActionPerformed
        // TODO add your handling code here:
        dispose();
        CadastroTreino treino = new CadastroTreino();
        treino.setVisible(true);
    }//GEN-LAST:event_jbNovoTreinoActionPerformed

    private void TabelaTreinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaTreinoMouseClicked
        // TODO add your handling code here:
        linha = TabelaTreino.getSelectedRow();
        jbEditarTreino.setEnabled(true);
        CodigoEdit = Integer.parseInt((String)TabelaTreino.getValueAt(linha, 2));
    }//GEN-LAST:event_TabelaTreinoMouseClicked

    private void jbPesquisarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarTreinoActionPerformed
        // TODO add your handling code here:
        if (!jtxPesquisaTreino.getText().trim().equals("")){
            CadastroTreinoModel treino = new CadastroTreinoModel();
            treino.setModalidade(jtxPesquisaTreino.getText());
            TreinoController controller = new TreinoController();
            ArrayList<CadastroTreinoModel> lista = controller.selecionarTodosModalidadesTreinos(treino);
            if(!lista.isEmpty()){
                DefaultTableModel modelo = (DefaultTableModel)TabelaTreino.getModel();
                modelo.setRowCount(0);
                for(CadastroTreinoModel t: lista){
                    modelo.addRow(new String[]{
                        String.valueOf(t.getIdaluno_fk().getCodigoAluno()),
                        t.getIdaluno_fk().getNomeAluno(),
                        String.valueOf(t.getCodigoTreino()),
                        t.getModalidade(),
                        t.getDescricao(),
                        t.getDuracao(),
                        t.getEsforço(),
                        String.valueOf(t.getFreqCardiaca()),
                        String.valueOf(t.getGastoCalorico())
                    });
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Pesquisar", 
                            "Retorno", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbPesquisarTreinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void atualizarTabela(){
        TreinoController treino = new TreinoController();
        ArrayList<CadastroTreinoModel> lista = treino.selecionarTodosTreinos();
        if(!lista.isEmpty()){
            DefaultTableModel modelo = (DefaultTableModel)TabelaTreino.getModel();
            modelo.setRowCount(0);
            for(CadastroTreinoModel t: lista){
                modelo.addRow(new String[]{
                    String.valueOf(t.getIdaluno_fk().getCodigoAluno()),
                    t.getIdaluno_fk().getNomeAluno(),
                    String.valueOf(t.getCodigoTreino()),
                    t.getModalidade(),
                    t.getDescricao(),
                    t.getDuracao(),
                    t.getEsforço(),
                    String.valueOf(t.getFreqCardiaca()),
                    String.valueOf(t.getGastoCalorico())
                });
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lampada;
    private javax.swing.JPanel Painel2;
    private javax.swing.JPanel PainelPesquisa;
    private javax.swing.JTable TabelaTreino;
    private javax.swing.JScrollPane Warning;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbCancelarTreino;
    private javax.swing.JButton jbEditarTreino;
    private javax.swing.JButton jbNovoTreino;
    private javax.swing.JButton jbPesquisarTreino;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmiAluno;
    private javax.swing.JMenuItem jmiEquipamentos;
    private javax.swing.JMenuItem jmiInstrutores;
    private javax.swing.JMenuItem jmiTreinos;
    private javax.swing.JTextField jtxPesquisaTreino;
    // End of variables declaration//GEN-END:variables
}
